name: gymflowclient
description: GymFlow â€” App para alumnos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.2.0

  # State management
  provider: ^6.1.2

  # HTTP
  http: ^1.2.1

  # Shared preferences (non-sensitive data)
  shared_preferences: ^2.2.3

  # Local file storage (for caching gym logo bytes)
  path_provider: ^2.1.3

  # Icons
  cupertino_icons: ^1.0.8

  # Date formatting
  intl: ^0.19.0

  # QR camera scanner (Android / iOS only)
  mobile_scanner: ^6.0.0

  # HTML renderer for rich-text portal blocks
  flutter_html: ^3.0.0-beta.2

  # Firebase & Push Notifications
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0d0e14"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  web:
    generate: false
  windows:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
